import Navbar from "@/components/Navbar";
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'True Feedback',
  description: 'Generated by Next.js',
}

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      {children}
      <Toaster
        position="bottom-right"
        reverseOrder={false}
      />
    </div>
  );
}